In [2]:
import numpy as np

In [3]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
valoraciones[0][1]

np.int64(7)

In [5]:
valoraciones[0,1]

np.int64(7)

In [6]:
valoraciones2 = np.array([[[8,7,8,5],[2,6,8,1]],[[8,8,9,5],[8,7,8,5]],[[2,6,8,1],[8,8,9,5]]])

In [7]:
valoraciones2[0,1,2]

np.int64(8)

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7.,  9.,  2.]],

       [[ 9.,  9., 10.,  6.],
        [ 9.,  8.,  9.,  6.]],

       [[ 3.,  7.,  9.,  2.],
        [ 9.,  9., 10.,  6.]]])

In [16]:
np.mean(valoraciones2)

np.float64(6.25)

In [17]:
np.mean(valoraciones2,axis=0)

array([[6.        , 7.        , 8.33333333, 3.66666667],
       [6.        , 7.        , 8.33333333, 3.66666667]])